import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed top-0 left-0 p-3">
          <Link href="/" className="text-white  px-3 text-xl">
            Torus
          </Link>
          <Link href="/blob" className="text-white px-3 text-xl">
            Blob
          </Link>
          <Link href="/blob/trans" className="text-white px-3 text-xl">
            and...
          </Link>
        </div>
      </body>
    </html>
  );
}
